Fix missing identifier check in ace-permissions and jobsync modules
Sonoran-Software/sonorancms_core pull request #27
Opened 2023-12-19 22:23 UTC by Jordan2139

2023-12-19 22:29 UTC, Fireant456 requested changes
Please see in line comments for quick revisions.

2023-12-19 22:29 UTC, Fireant456 commented on sonorancms/server/modules/ace-permissions/ace-permissions_sv.lua
> +			TriggerClientEvent('chat:addMessage', src, {color = {255, 0, 0}, multiline = true, args = {'SonoranPermissions', 'You must have a ' .. Config.apiIdType .. ' identifier to use this command.'}})
Change "SonoranPermissions" to "SonoranCMS"

2023-12-19 22:29 UTC, Fireant456 commented on sonorancms/server/modules/jobsync/jobsync_sv.lua
> +			TriggerClientEvent('chat:addMessage', src, {color = {255, 0, 0}, multiline = true, args = {'SonoranPermissions', 'You must have a ' .. Config.apiIdType .. ' identifier to use this command.'}})
Change "SonoranPermissions" to "SonoranCMS"

2023-12-19 22:36 UTC, Fireant456 approved these changes
QA Pass, but waiting on https://app.clickup.com/t/867965dc5 (CMS Core Updater logic rework to not overwrite module config files) for release

2024-01-31 23:56 UTC, DawsonGodin approved these changes

2024-01-31 23:56 UTC, DawsonGodin approved these changes

2024-02-01 00:04 UTC, merged